### ISSUE TITLE
Parsing approach

### ISSUE THREAD

**Issue by ivan-kleshnin** [nrjdalal/google-parser#2]
Hi Neeraj. I see that this parser relies on hardcoded classnames like `.co8aDb`. Have you figured out if those classes are more or less permanent? I mean: if they are some per-release / per-build hashes – this parser can break any moment. And if they are hashes of e.g. internal classnames that rotate relatively rare – it's another story.

I'm considering to use the library but I'm concerned about this aspect.

**Comment by nrjdalal** [comment]
these classes are there for a few years, no changes so far, you can safely use it :)

**Comment by ivan-kleshnin** [comment]
Ok, thank you for the information!
