### ISSUE TITLE
Pagination Request

### ISSUE THREAD

**Issue by stabla** [nrjdalal/google-parser#3]
Hi nrjdalal,

Very nicely done! I'm looking for a good scraping solution but there are not so many out there! Scraping Google search results is not an easy thing and I love your straightforward approach! 

I would have a question regarding the pagination system, the results I get through google-parse seem to be limited to 30 results so far, any idea if you plan to extend it with some pagination mechanisms? 

Thanks

**Comment by nrjdalal** [comment]
the results are upto 100 if available for given region or keyword, usually 60-70 results are there, some of the results are of different kind, current I'm not scraping for data, if and when I get back to it, I will add more kind of results

**Comment by stabla** [comment]
Thanks a lot for your fast reply!
